#!/usr/bin/env bash
#3. Redirection
sudo apt-get update -y
sudo apt-get install nginx -y
sudo ufw allow "Nginx HTTP"
sudo echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo sed -i "
sudo service nginx restart
