#!/usr/bin/env bash
#3. Redirection
sudo apt-get update -y
sudo apt-get install nginx -y
sudo ufw allow "Nginx HTTP"
sudo echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo sed -i '24i\       rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
