#!/usr/bin/env bash
#Install your load balancer
sudo apt-get update
sudo apt-get install --no-install-recommends software-properties-common -y
sudo add-apt-repository ppa:vbernat/haproxy-2.8 -y
sudo apt-get update -y
sudo apt-get install haproxy=2.8.\*

echo "****Make a copy of orgignal file******"
if [ ! -f "/etc/haproxy/haproxy.cfg.tmp" ]; then
	sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.tmp
fi

echo \
"

backend nodes
    balance roundrobin
	server 467867-web-01 52.72.66.73:80 check
	server 467867-web-02 34.227.91.227:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg

echo '******* restart haproxy *********'
sudo service haproxy restart
