#!/usr/bin/env bash
# backup and compress my databases


day=$(date +"%d")
month=$(date +"%m")
year=$(date +"%Y")
file_name="$day-$month-$year.tar.gz"
mysqldump -u root -p --all-databases > backup.sql
tar -czvf "$file_name" backup.sql
